
package com.enterprise.fizzbuzz.soa.client.printline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrintLineService", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", wsdlLocation = "http://localhost:8080/PrintLineService/PrintLine?wsdl")
public class PrintLineService
    extends Service
{

    private final static URL PRINTLINESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRINTLINESERVICE_EXCEPTION;
    private final static QName PRINTLINESERVICE_QNAME = new QName("http://ws.soa.fizzbuzz.enterprise.com/", "PrintLineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PrintLineService/PrintLine?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRINTLINESERVICE_WSDL_LOCATION = url;
        PRINTLINESERVICE_EXCEPTION = e;
    }

    public PrintLineService() {
        super(__getWsdlLocation(), PRINTLINESERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns PrintLine
     */
    @WebEndpoint(name = "PrintLinePort")
    public PrintLine getPrintLinePort() {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "PrintLinePort"), PrintLine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintLine
     */
    @WebEndpoint(name = "PrintLinePort")
    public PrintLine getPrintLinePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "PrintLinePort"), PrintLine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRINTLINESERVICE_EXCEPTION!= null) {
            throw PRINTLINESERVICE_EXCEPTION;
        }
        return PRINTLINESERVICE_WSDL_LOCATION;
    }

}
