
package com.enterprise.fizzbuzz.soa.client.lessthanorequalto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LessThanOrEqualToService", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", wsdlLocation = "http://localhost:8080/LessThanOrEqualToService/LessThanOrEqualTo?wsdl")
public class LessThanOrEqualToService
    extends Service
{

    private final static URL LESSTHANOREQUALTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException LESSTHANOREQUALTOSERVICE_EXCEPTION;
    private final static QName LESSTHANOREQUALTOSERVICE_QNAME = new QName("http://ws.soa.fizzbuzz.enterprise.com/", "LessThanOrEqualToService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LessThanOrEqualToService/LessThanOrEqualTo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LESSTHANOREQUALTOSERVICE_WSDL_LOCATION = url;
        LESSTHANOREQUALTOSERVICE_EXCEPTION = e;
    }

    public LessThanOrEqualToService() {
        super(__getWsdlLocation(), LESSTHANOREQUALTOSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns LessThanOrEqualTo
     */
    @WebEndpoint(name = "LessThanOrEqualToPort")
    public LessThanOrEqualTo getLessThanOrEqualToPort() {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "LessThanOrEqualToPort"), LessThanOrEqualTo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LessThanOrEqualTo
     */
    @WebEndpoint(name = "LessThanOrEqualToPort")
    public LessThanOrEqualTo getLessThanOrEqualToPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "LessThanOrEqualToPort"), LessThanOrEqualTo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LESSTHANOREQUALTOSERVICE_EXCEPTION!= null) {
            throw LESSTHANOREQUALTOSERVICE_EXCEPTION;
        }
        return LESSTHANOREQUALTOSERVICE_WSDL_LOCATION;
    }

}
