
package com.enterprise.fizzbuzz.soa.client.modulus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModulusService", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", wsdlLocation = "http://localhost:8080/ModulusService/Modulus?wsdl")
public class ModulusService
    extends Service
{

    private final static URL MODULUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODULUSSERVICE_EXCEPTION;
    private final static QName MODULUSSERVICE_QNAME = new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ModulusService/Modulus?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULUSSERVICE_WSDL_LOCATION = url;
        MODULUSSERVICE_EXCEPTION = e;
    }

    public ModulusService() {
        super(__getWsdlLocation(), MODULUSSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns Modulus
     */
    @WebEndpoint(name = "ModulusPort")
    public Modulus getModulusPort() {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusPort"), Modulus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Modulus
     */
    @WebEndpoint(name = "ModulusPort")
    public Modulus getModulusPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusPort"), Modulus.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULUSSERVICE_EXCEPTION!= null) {
            throw MODULUSSERVICE_EXCEPTION;
        }
        return MODULUSSERVICE_WSDL_LOCATION;
    }

}
