
package com.enterprise.fizzbuzz.soa.client.integertostring;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegerToStringService", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", wsdlLocation = "http://localhost:8080/IntegerToStringService/IntegerToString?wsdl")
public class IntegerToStringService
    extends Service
{

    private final static URL INTEGERTOSTRINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGERTOSTRINGSERVICE_EXCEPTION;
    private final static QName INTEGERTOSTRINGSERVICE_QNAME = new QName("http://ws.soa.fizzbuzz.enterprise.com/", "IntegerToStringService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/IntegerToStringService/IntegerToString?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGERTOSTRINGSERVICE_WSDL_LOCATION = url;
        INTEGERTOSTRINGSERVICE_EXCEPTION = e;
    }

    public IntegerToStringService() {
        super(__getWsdlLocation(), INTEGERTOSTRINGSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns IntegerToString
     */
    @WebEndpoint(name = "IntegerToStringPort")
    public IntegerToString getIntegerToStringPort() {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "IntegerToStringPort"), IntegerToString.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegerToString
     */
    @WebEndpoint(name = "IntegerToStringPort")
    public IntegerToString getIntegerToStringPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "IntegerToStringPort"), IntegerToString.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGERTOSTRINGSERVICE_EXCEPTION!= null) {
            throw INTEGERTOSTRINGSERVICE_EXCEPTION;
        }
        return INTEGERTOSTRINGSERVICE_WSDL_LOCATION;
    }

}
