
package com.enterprise.fizzbuzz.soa.client.integertostring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegerToString", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegerToString {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SomeObjectIsNullException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", className = "com.enterprise.fizzbuzz.soa.client.integertostring.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", className = "com.enterprise.fizzbuzz.soa.client.integertostring.ToStringResponse")
    @Action(input = "http://ws.soa.fizzbuzz.enterprise.com/IntegerToString/toStringRequest", output = "http://ws.soa.fizzbuzz.enterprise.com/IntegerToString/toStringResponse", fault = {
        @FaultAction(className = SomeObjectIsNullException_Exception.class, value = "http://ws.soa.fizzbuzz.enterprise.com/IntegerToString/toString/Fault/SomeObjectIsNullException")
    })
    public String toString(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0)
        throws SomeObjectIsNullException_Exception
    ;

}
