
package com.enterprise.fizzbuzz.soa.client.moduluscondition;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModulusConditionService", targetNamespace = "http://ws.soa.fizzbuzz.enterprise.com/", wsdlLocation = "http://localhost:8080/ModulusConditionService/ModulusCondition?wsdl")
public class ModulusConditionService
    extends Service
{

    private final static URL MODULUSCONDITIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODULUSCONDITIONSERVICE_EXCEPTION;
    private final static QName MODULUSCONDITIONSERVICE_QNAME = new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusConditionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ModulusConditionService/ModulusCondition?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULUSCONDITIONSERVICE_WSDL_LOCATION = url;
        MODULUSCONDITIONSERVICE_EXCEPTION = e;
    }

    public ModulusConditionService() {
        super(__getWsdlLocation(), MODULUSCONDITIONSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns ModulusCondition
     */
    @WebEndpoint(name = "ModulusConditionPort")
    public ModulusCondition getModulusConditionPort() {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusConditionPort"), ModulusCondition.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModulusCondition
     */
    @WebEndpoint(name = "ModulusConditionPort")
    public ModulusCondition getModulusConditionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.fizzbuzz.enterprise.com/", "ModulusConditionPort"), ModulusCondition.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULUSCONDITIONSERVICE_EXCEPTION!= null) {
            throw MODULUSCONDITIONSERVICE_EXCEPTION;
        }
        return MODULUSCONDITIONSERVICE_WSDL_LOCATION;
    }

}
